# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    depend_on_referenced_packages: ignore
  plugins:
    - custom_lint

linter:
  rules:
    avoid_print: false  # Disable the `avoid_print` rule
    prefer_single_quotes: true  # Enable the `prefer_single_quotes` rule
