name: code_con_fe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  material_design_icons_flutter: ^7.0.7296
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  custom_lint: ^0.7.0
  flutter_markdown: ^0.7.4+1
  go_router: ^14.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
